# name
name: my-app

# host
host: 0.0.0.0

# port
port: 4000

# secret
secretKey: kenotejs

# Redis
redisOpts:
  host: 127.0.0.1
  port: 6379
  db: 0

# Database
dbOpts:
  type: postgres
  host: localhost
  port: 5432
  username: postgres
  password: postgres
  database: kenotejs-use-typeorm