version: '3.7'

services:
  app:
    image: kenotejs-use-mongoose:latest
    container_name: kenotejs-use-mongoose
    build: 
      context: .
      dockerfile: ./Dockerfile
    depends_on:
      - redis
      - mongodb
    environment:
      - NODE_ENV=production
    volumes:
      - ${PWD}/.docker/config:/usr/src/app/config
      - ${PWD}/.docker/logs:/usr/src/app/logs
      - ${PWD}/.docker/mock:/usr/src/app/mock
      - ${PWD}/.docker/static:/usr/src/app/static
      - ${PWD}/.docker/views:/usr/src/app/views
    ports:
      - 4000:4000
    networks:
      - webnet

  mongodb:
    image: mongo:4.4.12
    container_name: mongodb
    restart: always
    volumes:
      - kenotejs-mongo:/var/lib/mongo/data
    networks:
      - webnet
    ports:
      - 37017:27017

  redis:
    image: redis:6.2.6
    container_name: redis
    command: redis-server --appendonly yes
    volumes:
      - kenotejs-redis:/var/lib/redis/data
    networks:
      - webnet
    ports:
      - 9379:6379
    
volumes:
  kenotejs-mongo:
  kenotejs-redis:

networks:
  webnet:
    driver: bridge